AppName: Linux Package Maker
AppDirectory: LPM
Launcher: lpm
ShortDescription: Linux Package Maker
Description: Package maker for any Linux apps
Terminal: false
Category: Development
Command: lpm
DesktopIcon: true
CompressionMode: xz
Icon: lpm.png
